site_name: Deep RL Course
site_url: https://DeepRL2026.github.io
theme:
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: black
      accent: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    # - navigation.indexes

plugins:
  - search
  # - blog:
  #     blog_toc: true
  #     post_readtime_words_per_minute: 250
  #     pagination_per_page: 5
  #     archive: true
  #     archive_name: Archive
  #     archive_date_format: MMMM yyyy
  #     archive_url_date_format: yyyy/MM
  #     archive_pagination_per_page: 10
  #     archive_toc: false
  #     categories_pagination_per_page: 10
  #     categories_toc: false
  # - tags:
  #     tags_file: blog/tags.md
  - social
  # - offline

extra:
  generator: false
  analytics:
    provider: google
    property: G-Q1YT8K39WE
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  disable_toc_integrate_paths:
    - course_notes
    - prerequisites


copyright: Made with ❤️ in Robust and Interpretable Machine Learning Lab

nav:
  - Home:
    - index.md
  - Course Notes:
    - index.md
    # - Conceptual Overview of RL:
    #   - course_notes/intro-to-rl.md
    #   - course_notes/value-based.md
    #   - course_notes/policy-based.md
    #   - course_notes/advanced.md
    #   - course_notes/model-based.md
    #   - course_notes/bandits.md
  - Lectures:
    - lectures/index.md
    - lectures/lecture1.md
    - lectures/lecture2.md
    # - lectures/week3.md
    # - lectures/week4.md
    # - lectures/week5.md
    # - lectures/week6.md
    # - lectures/week7.md
    # - lectures/week8.md
    # - lectures/week9.md
    # - lectures/week10.md
    # - lectures/week11.md
    # - lectures/week12.md
    # - lectures/week13.md
    # - lectures/week14.md
    # - lectures/week15.md
  - TA Sessions:
    - index.md

  # - Screen Records:
  #   - screen/index.md

  - Homeworks:
    - index.md

  - Projects:
    - index.md

  - Exams:
    # - exams/midterm.md
    # - exams/final.md
    - exams/index.md

  - Resources:
    - resources/index.md

extra_css:
  - stylesheets/extra.css
  - stylesheets/vazirmatn.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - extra
  - admonition

  - pymdownx.details



